baseURL = 'https://leorium.com/'
languageCode = 'en-us'
title = 'leorium.com'
enableEmoji = true
summaryLength = 70
# Use the custom theme
theme = "bloat-free-theme"

[pagination]
  pagerSize = 5

[params]
  description = "Hi. Welcome to my website!"
  author = "Leorium"
  mainSections = ["posts"]
  youtubeChannel = "@leorium"
  githubHandle = "LeoriumDev"
  dateFormat = "Jan 2, 2006"
  showReadingTime = true
  showPostNavigation = true
  math = true
  
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "series"
    name = "Series"
    url = "/series/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 5

[taxonomies]
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]